// Code generated by goctl. DO NOT EDIT.
package types

type CommonRsp struct {
	Code int    `json:"code"`
	Msg  string `json:"msg,default=ok"`
}

type ImgReq struct {
	Token      string `header:"token"`
	BinaryData string `json:"binaryData,optional,omitempty"`
	URL        string `json:"url,optional,omitempty"`
	Action     string `json:"action"`
	ExtraInfo  string `json:"extraInfo,optional,omitempty"`
	TimeStamp  int64  `json:"timestamp"`
}

type ImgRsp struct {
	CommonRsp
	BinaryData string `json:"binaryData"`
	URL        string `json:"url"`
}
